name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  static-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install pre-commit
        run: pip install pre-commit

      - name: Run Static Tests
        run: pre-commit run --all-files --show-diff-on-failure
